apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: processer
  name: processer
  namespace: mynamespace
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do ps -ef >> /var/log/my.log; sleep 1; done 
    image: busybox
    name: processer
    volumeMounts:
            - name: vol
              mountPath: /var/log
    resources: {}
  dnsPolicy: ClusterFirst
  volumes:
          - name: vol
            persistentVolumeClaim:
                    claimName: task-pv-claim 
  restartPolicy: Always
status: {}
